BenevArts/BenevArts/BenevArts.Web/Controllers/AssetController.cs
using BenevArts.Common;
using BenevArts.Services.Data.Interfaces;
using BenevArts.Web.Infrastructure;
using BenevArts.Web.ViewModels.Home;

using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;

namespace BenevArts.Web.Controllers
{
	public class AssetController : BaseController
	{
		private readonly IAssetService assetService;
		private readonly ILikeService likeService;
		private readonly ILogger<AssetController> logger;

		public AssetController(IAssetService _assetService,
			ILikeService _likeService,
			ILogger<AssetController> _logger)
		{
			assetService = _assetService;
			likeService = _likeService;
			logger = _logger;
		}

		// Get

		[HttpGet]
		[AllowAnonymous]
		public async Task<IActionResult> All(string sortOrder, int page = 1, int itemsPerPage = 1)
		{
			try
			{
				if (!Validations.IsValidQuery(sortOrder))
				{
					return View();
				}

				IEnumerable<AssetViewModel> models = await assetService.GetAllAssetsAsync();

				ViewData["CurrentSortOrder"] = sortOrder;

				return View(Pagination.Paginator(models, null, -1, page, itemsPerPage, sortOrder));
			}
			catch (Exception ex)
			{
				logger.LogError(ex, "An exception occurred in the All action.");
				return View("Error"); // Display a generic error view, for example
			}
		}

		[HttpGet]
		[AllowAnonymous]
		public async Task<IActionResult> Search(string sortOrder, string query, int page = 1, int itemsPerPage = 1)
		{
			try
			{
				if (!Validations.IsValidQuery(sortOrder))
				{
					return View();
				}

				// Check the query
				if (string.IsNullOrWhiteSpace(query))
				{
					return RedirectToAction(nameof(All));
				}
				if (!Validations.IsValidQuery(query))
				{
					ViewData["InvalidInput"] = "Invalid input. Only letters and numbers are allowed.";

					return View();
				}

				ViewData["CurrentSortOrder"] = sortOrder;

				IEnumerable<AssetViewModel> models = await assetService.GetSearchResultAsync(query);

				if (models == null)
				{
					return View();
				}

				return View("~/Views/Asset/All.cshtml", Pagination.Paginator(models, query, -1, page, itemsPerPage, sortOrder));
			}
			catch (Exception ex)
			{
				logger.LogError(ex, "An exception occurred in the Search action.");
				return View("Error");
			}

		}

		[HttpGet]
		[AllowAnonymous]
		public async Task<IActionResult> Details(Guid id)
		{
			try
			{
				AssetViewModel model = await assetService.GetAssetByIdAsync(id, GetUserId());

				return View(model);
			}
			catch (Exception ex)
			{
				logger.LogError(ex, "An exception occurred in the Details action.");
				return View("Error");
			}
		}

		[HttpGet]
		[AllowAnonymous]
		public async Task<IActionResult> Download(Guid assetId)
		{
			try
			{
				if (!User.Identity?.IsAuthenticated ?? true)
				{
					return View("~/Areas/Identity/Pages/Account/Login.cshtml");
				}
				AssetViewModel asset = await assetService.GetAssetByIdAsync(assetId, GetUserId());

				string filePath = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot", "ZipFiles", asset.ZipFileName)
					?? throw new InvalidOperationException("The file was not found!");

				var fileStream = new FileStream(filePath, FileMode.Open, FileAccess.Read);
				return File(fileStream, "application/zip", asset.ZipFileName);
			}
			catch (Exception ex)
			{
				logger.LogError(ex, "An exception occurred in the Download action.");
				return View("Error");
			}
		}

		// Post

		[HttpPost]
		[Authorize(Roles = "User,Seller,Admin")]
		public async Task<IActionResult> ToggleLike(Guid assetId, bool isLiked)
		{
			try
			{
				// Toggle the like status for the asset
				if (isLiked)
				{
					await likeService.RemoveLikeAsync(assetId, GetUserId());
				}
				else
				{
					await likeService.AddLikeAsync(assetId, GetUserId());
				}

				bool updatedIsLiked = await likeService.IsLikedByUserAsync(assetId, GetUserId());
				int updatedLikeCount = await likeService.GetLikeCountAsync(assetId);

				return Json(new { success = true, isLiked = updatedIsLiked, likeCount = updatedLikeCount });
			}
			catch (Exception ex)
			{
				logger.LogError(ex, "An exception occurred in the ToggleLike action.");
				return View("Error");
			}
		}
	}
}

BenevArts/BenevArts/BenevArts.Web/Controllers/CategoryController.cs
using BenevArts.Common;
using BenevArts.Services.Data.Interfaces;
using BenevArts.Web.Infrastructure;
using BenevArts.Web.ViewModels.Home;

using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;

namespace BenevArts.Web.Controllers
{
	public class CategoryController : BaseController
	{
		private readonly ICategoryService categoryService;
		private readonly ILogger<CategoryController> logger;

		public CategoryController(ICategoryService _categoryService, ILogger<CategoryController> _logger)
		{
			categoryService = _categoryService;
			logger = _logger;
		}

		[HttpGet]
		[AllowAnonymous]
		public async Task<IActionResult> Index()
		{
			try
			{
				IEnumerable<CategoryViewModel> categories = await categoryService.GetCategoriesViewAsync();

				return View(categories);
			}
			catch (Exception ex)
			{
				logger.LogError(ex, "An exception occurred in the Index action.");
				return View("Error");
			}
		}


		[HttpGet]
		[AllowAnonymous]
		public async Task<IActionResult> Assets(string sortOrder, int categoryId, int page = 1, int currentPage = 1)
		{
			try
			{
				if (!Validations.IsValidQuery(sortOrder))
				{
					return View();
				}

				IEnumerable<AssetViewModel> assets = await categoryService.
					GetAssetsByCategoryIdAsync(categoryId);

				ViewData["CurrentSortOrder"] = sortOrder;

				return View("~/Views/Asset/All.cshtml",
					Pagination.Paginator(assets, null, categoryId, page, currentPage, sortOrder));
			}
			catch (Exception ex)
			{
				logger.LogError(ex, "An exception occurred in the Assets action.");
				return View("Error");
			}
		}
	}
}

BenevArts/BenevArts/BenevArts.Web/Controllers/SellerController.cs
using BenevArts.Common;
using BenevArts.Services.Data.Interfaces;
using BenevArts.Web.ViewModels.Home;

using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;


namespace BenevArts.Web.Controllers
{
	public class SellerController : BaseController
	{
		private readonly ISellerService sellerService;
		private readonly ILogger<SellerController> logger;

		public SellerController(ISellerService _sellerService, ILogger<SellerController> _logger)
		{
			sellerService = _sellerService;
			logger = _logger;
		}

		// GET
		[HttpGet]
		[Authorize(Roles = "User,Admin")]
		public async Task<IActionResult> Apply()
		{
			try
			{
				if (!await sellerService.CheckIfUserAppliedAsync(Guid.Parse(GetUserId())))
				{
					return View();
				}
				return RedirectToAction(nameof(StillReviewing));
			}
			catch (Exception ex)
			{
				logger.LogError(ex, "An exception occurred in the Apply action.");
				return View("Error");
			}
		}

		[HttpGet]
		[Authorize(Roles = "User,Admin")]
		public IActionResult ThankYou()
		{
			return View();
		}

		[HttpGet]
		[Authorize(Roles = "User,Admin")]
		public IActionResult StillReviewing()
		{
			return View();
		}

		[HttpGet]
		[Authorize(Roles = "Admin")]
		public async Task<IActionResult> AllApplications()
		{
			try
			{
				IEnumerable<SellerApplicationViewModel> models = await sellerService.GetAllApplicationsAsync();

				return View("~/Views/Seller/AllApplications.cshtml", models);
			}
			catch (Exception ex)
			{
				logger.LogError(ex, "An exception occurred in the AllApplications action.");
				return View("Error");
			}
		}

		[HttpGet]
		[Authorize(Roles = "Admin")]
		public async Task<IActionResult> GetApplicationsByState(string state)
		{
			try
			{
				IEnumerable<SellerApplicationViewModel> applications;

				// Retrieve applications based on the selected state
				if (string.IsNullOrEmpty(state) || !Validations.IsValidQuery(state))
				{
					applications = await sellerService.GetAllApplicationsAsync();
				}
				else
				{
					applications = await sellerService.GetApplicationsByStateAsync(state);

				}

				// Return a partial view with the filtered applications data
				return PartialView("_ApplicationsTable", applications);
			}
			catch (Exception ex)
			{
				logger.LogError(ex, "An exception occurred in the GetApplicationByState action.");
				return View("Error");
			}
		}

		[HttpGet]
		[Authorize(Roles = "Admin")]
		public async Task<IActionResult> SingleApplication(int id)
		{
			try
			{
				SellerApplicationViewModel model = await sellerService.GetSingleApplicationAsync(id);

				return View("~/Views/Seller/SingleApplication.cshtml", model);
			}
			catch (Exception ex)
			{
				logger.LogError(ex, "An exception occurred in the SingleApplication action.");
				return View("Error");
			}
		}

		[HttpGet]
		[Authorize(Roles = "Admin")]
		public async Task<IActionResult> ApproveApplication(int id)
		{
			try
			{
				await sellerService.ApproveApplicationAsync(id);

				// TO DO: Send Notification to the user

				return RedirectToAction(nameof(AllApplications));
			}
			catch (Exception ex)
			{
				logger.LogError(ex, "An exception occurred in the ApproveApplication action.");
				return View("Error");
			}
		}

		[HttpGet]
		[Authorize(Roles = "Admin")]
		public async Task<IActionResult> DeclineApplication(int id)
		{
			try
			{
				await sellerService.DeclineApplicationAsync(id);

				// TO DO: Send Notification to the user

				return RedirectToAction(nameof(AllApplications));
			}
			catch (Exception ex)
			{
				logger.LogError(ex, "An exception occurred in the DeclineApplication action.");
				return View("Error");
			}
		}

		// POST
		[HttpPost]
		[Authorize(Roles = "User,Admin")]
		public async Task<IActionResult> Apply(SellerApplicationViewModel application)
		{
			try
			{
				if (ModelState.IsValid &&
					!await sellerService.CheckIfUserAppliedAsync(Guid.Parse(GetUserId())))
				{
					await sellerService.ApplyAsync(application, GetUserId());
					return RedirectToAction(nameof(ThankYou));
				}
				return View();
			}
			catch (Exception ex)
			{
				logger.LogError(ex, "An exception occurred in the Details action.");
				return View("Error");
			}
		}
	}
}

BenevArts/BenevArts/BenevArts.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="utf-8" />
	<meta name="viewport" content="width=device-width, initial-scale=1.0" />
	<title>@ViewData["Title"] - BenevArts</title>
	<link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
	<link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
	<link rel="stylesheet" href="~/BenevArts.styles.css" asp-append-version="true" />
</head>

<body>
	<nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-primary border-bottom box-shadow mb-3">
		<div class="container-fluid">
			<a class="navbar-brand" asp-area="" asp-controller="Category" asp-action="Index">BenevArts</a>
			<button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
					aria-expanded="false" aria-label="Toggle navigation">
				<span class="navbar-toggler-icon"></span>
			</button>
			<div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
				<ul class="navbar-nav mr-auto">
					<li class="nav-item">
						<a class="nav-link text-dark" asp-area="" asp-controller="Asset" asp-action="All">Find Assets</a>
					</li>

					@if (User.IsInRole("User"))
					{
						<li class="nav-item">
							<a class="nav-link text-dark" asp-area="" asp-controller="Seller" asp-action="Apply">Become a Seller</a>
						</li>
					}
				</ul>

				<partial name="_LoginPartial" />
			</div>
		</div>
	</nav>
	<div class="container">
		<main role="main" class="pb-3">
			@{
				var invalidInputError = ViewData["InvalidInput"] as string;
			}
			@if (!string.IsNullOrEmpty(invalidInputError))
			{
				<div class="alert alert-danger">@invalidInputError</div>
			}
			<form asp-controller="Asset" asp-action="Search" method="get" class="form-inline d-flex justify-content-center border-bottom">
				<input type="text" name="query" class="form-control mr-6 mb-2" style="width: 500px;" placeholder="Search...">
				<button type="submit" class="btn btn-primary ml-2 mb-2">Search</button>
			</form>

			@RenderBody()
		</main>
	</div>

	<footer class="border-top footer text-muted">
		<div class="container">
			&copy; 2023 - BenevArts - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
		</div>
	</footer>
	<script src="~/lib/jquery/dist/jquery.min.js"></script>
	<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
	@await RenderSectionAsync("Scripts", required: false)
</body>
</html>